version: '3'

services:

  postgres:
    ports:
      - "5432:5432"
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_password
      POSTGRES_DB: dbt
    volumes:
      - ./postgres:/var/lib/postgresql
    networks:
      - airflow-network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - airflow-network

  airflow-dbt:
    image: airflow-dbt:latest
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./airflow:/root/airflow
      - ./dbt:/root/dbt
    networks:
      - airflow-network
    command:
      - /bin/sh
      - -c
      - |
        cd /root/dbt
        dbt init test_project -s
        cd /root/dbt/test_project
        dbt run
        dbt docs generate
        mkdir /root/airflow/dags
        mv /tmp/test_dbt.py /root/airflow/dags/test_dbt.py
        airflow standalone

networks:
  airflow-network:
    driver: bridge