FROM python

RUN apt update
RUN apt upgrade -y

RUN apt install vim -y
RUN apt install less -y


# setup airflow
RUN mkdir /root/airflow
RUN mkdir /root/airflow/dags
RUN export AIRFLOW_HOME=~/airflow
RUN pip install apache-airflow

# setup dbt 
RUN pip install dbt-postgres
RUN mkdir /root/dbt
COPY profiles.yml /root/.dbt/profiles.yml
COPY test_dbt.py /tmp/test_dbt.py

EXPOSE 8080